spring.application.name=template

template.agent.request.path=/api/v1/test/Agent/**
template.dso.request.path=/api/v1/test/DSO/**
aws.region=ap-southeast-1
aws.access.key=test
aws.secret.key=test
aws.secret.manager.name=agentLoan-secret