spring.application.name=template

template.agent.request.path=/api/v1/test/Agent/**
template.dso.request.path=/api/v1/test/DSO/**
aws.region=US_EAST_1
aws.access.key=ACCESS_KEY
aws.secret.key=SECRET_KEY
